CREATE TABLE `t_species` (
  `id_species` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `average_height` decimal(10,2) DEFAULT NULL,
  `average_lifespan` int(11) DEFAULT NULL,
  `classification` varchar(255) DEFAULT NULL,
  `designation` varchar(255) DEFAULT NULL,
  `eye_colors` varchar(255) DEFAULT NULL,
  `hair_colors` varchar(255) DEFAULT NULL,
  `homeworld` varchar(255) DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `people` json DEFAULT NULL,
  `films` json DEFAULT NULL,
  `skin_colors` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `timestamp_modified` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `timestamp_created` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id_species`),
  UNIQUE KEY `t_species_UN` (`name`),
  KEY `t_species_timestamp_modified_IDX` (`timestamp_modified`) USING BTREE,
  KEY `t_species_timestamp_created_IDX` (`timestamp_created`) USING BTREE,
  KEY `t_species_name_IDX` (`name`) USING BTREE,
  KEY `t_species_average_height_IDX` (`average_height`) USING BTREE,
  KEY `t_species_average_lifespan_IDX` (`average_lifespan`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8